FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -g nodemon
RUN npm install
RUN npm install -g node-pre-gyp
COPY . .
RUN npm rebuild bcrypt --build-from-source

EXPOSE 3000

CMD ["npm", "start"]